name: Mypy
on:
  push:
    branches: 'main'
  pull_request:
jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mypy typer rich pytest
      - name: Run mypy
        run: python3 -m mypy g.py test_g.py
